name: Compilar TCC

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          work_in_root_file_dir: true
          latexmk_use_xelatex: false

      - uses: actions/upload-artifact@v4
        with:
          name: TCC-PDF
          path: main.pdf
